/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolIndexRouteImport } from './routes/school.index'
import { Route as SchoolClassIdRouteImport } from './routes/school.$classId'
import { Route as RankingClassIdRouteImport } from './routes/ranking.$classId'
import { Route as ClassClassIdRouteImport } from './routes/class.$classId'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolIndexRoute = SchoolIndexRouteImport.update({
  id: '/school/',
  path: '/school/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolClassIdRoute = SchoolClassIdRouteImport.update({
  id: '/school/$classId',
  path: '/school/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingClassIdRoute = RankingClassIdRouteImport.update({
  id: '/ranking/$classId',
  path: '/ranking/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/ranking/$classId': typeof RankingClassIdRoute
  '/school/$classId': typeof SchoolClassIdRoute
  '/school/': typeof SchoolIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/ranking/$classId': typeof RankingClassIdRoute
  '/school/$classId': typeof SchoolClassIdRoute
  '/school': typeof SchoolIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/ranking/$classId': typeof RankingClassIdRoute
  '/school/$classId': typeof SchoolClassIdRoute
  '/school/': typeof SchoolIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/class/$classId'
    | '/ranking/$classId'
    | '/school/$classId'
    | '/school/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/class/$classId'
    | '/ranking/$classId'
    | '/school/$classId'
    | '/school'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/class/$classId'
    | '/ranking/$classId'
    | '/school/$classId'
    | '/school/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  ClassClassIdRoute: typeof ClassClassIdRoute
  RankingClassIdRoute: typeof RankingClassIdRoute
  SchoolClassIdRoute: typeof SchoolClassIdRoute
  SchoolIndexRoute: typeof SchoolIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/': {
      id: '/school/'
      path: '/school'
      fullPath: '/school/'
      preLoaderRoute: typeof SchoolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$classId': {
      id: '/school/$classId'
      path: '/school/$classId'
      fullPath: '/school/$classId'
      preLoaderRoute: typeof SchoolClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/$classId': {
      id: '/ranking/$classId'
      path: '/ranking/$classId'
      fullPath: '/ranking/$classId'
      preLoaderRoute: typeof RankingClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  ClassClassIdRoute: ClassClassIdRoute,
  RankingClassIdRoute: RankingClassIdRoute,
  SchoolClassIdRoute: SchoolClassIdRoute,
  SchoolIndexRoute: SchoolIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
